### ISSUE TITLE
Dependency package versions

### ISSUE THREAD

**Issue by brigs** [condep/condep-dsl#5]
Some of the package dependencies in the [build script](https://github.com/condep/condep-dsl/blob/master/build/default.ps1) are locked to specific versions. Microsoft has released a new version of Microsoft.AspNet.WebApi.Client and condep does not seem to handle this. Should this package version be locked as well ?

**Comment by torresdal** [comment]
It might. Can I ask what kind of problem it causes or what caused this to
be a problem? Keep in mind the warning "Avoid mixing ConDep with your
existing projects" from the documentation here:
http://www.condep.io/docs/3-0/quick-start/

On Mon, Sep 21, 2015 at 3:37 PM, Anders <notifications@github.com> wrote:

> Some of the package dependencies in the build script
> <https://github.com/condep/condep-dsl/blob/master/build/default.ps1> are
> locked to specific versions. Microsoft has released a new version of
> Microsoft.AspNet.WebApi.Client and condep does not seem to handle this.
> Should this package version be locked as well ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/condep/condep-dsl/issues/5>.
>



-- 
/Jon A.

*sometimes i sit and think, and sometimes i just sit*
  - courtney barnett

**Comment by brigs** [comment]
We have a standalone deployment solution in this case. It causes "The located assembly's manifest definition does not match the assembly reference". I locked the version of Microsoft.AspNet.WebApi.Client on our local server and this fixed the issue. Am I missing some assembly redirect which should have been generated?

**Comment by torresdal** [comment]
Strange. The only binding redirect I know of (and which is in the dsl app.config) is for json.net - but this redirect I handle in code. It's probably a good idea to lock this down anyways, because it seams like web api don't respect semver (so can't do e.g. [4.0.20710.0,5) ). The next version of ConDep will be 5.0 and I'll make sure to lock it down there and/or upgrade to the latest version of the web api client. If it causes pain on your side I can patch condep.dsl with this version lock, unless that causes some other side effects...

**Comment by brigs** [comment]
We've been running with a locked package version for about two weeks now and haven't run into any issues. However, condep is not used on a grand scale (yet :-)) so there might indeed be some unknown issue(s). It does not cause any pain on our side and it's no problem waiting for the next major version of condep.
